### PR TITLE
fix: use +esm for vueuse >= 13

### LINKED ISSUE #18: BUG | Playground is not working for the alpha releases.
### Describe the bug

The currently playground (linked from the main docs page)

https://playground.vueuse.org/?vueuse=14.0.0-alpha.2#eNqFU01v2zAM/SuEMCAJkNqH7ZLWHboNPWzAumHdbj7UkWnHqSwZ+kgzGP7vpSXbcYt+wBeKfO/5kaJa9qVpooNDds4Sw3XVWDBoXQMik+VlyqxJ2edUAlR1o7SF1hm8tUpnJXZQaFVDyq6IT+mYK40p68FcSWPhkAlHYF3JEi7hRFwussUaFjsUQi1WF/CMcePqLeqnhC0RNpuNB/cfQOEkt5WS4Jo8s8Nvlito+yLM/x35mBzc6Uzm5NgESx/an5ndRSG5XHV3wUn3on4w9Uw/JCf9J3IXg1YSh7HSEOlgsW4EyfmRJnl1AC4yY2jQhcAjVFQ3ZxylRQ17Z2xV/B+PD2ckhChhNwTDxZBOMwQwtHYObTsbQEc2QjmJe+h0OvEApO9lYobWXmWS8xk32TpraVRXXFT8npqZ3wnZ/OePg7kkDuj3+cHDu/wkHt2MURLP5szWtMS0XkVVRnujJG26v8OUcVU3lUD9q+kvmhadug+iKctoNx9++JzVDtdjnu+Q37+Q35tjn0vZb40G9YEewlSzmS7RhvL17Q0eKZ6KtcqdIPQbxT9olHC9xwD76mROtmc47/a7f6E0ob/m+mhRmrGp3qjfRo9PGT3Xb2+0frL7Mfo0bHHHukf3ZGH4

Does not currently work. 

In the console we see this error: 

```
GET https://cdn.jsdelivr.net/npm/@vueuse/core@14.0.0-alpha.3/index.mjs net::ERR_ABORTED 404 (Not Found)
```

### Reproduction

https://playground.vueuse.org/?vueuse=14.0.0-alpha.2#eNqFU01v2zAM/SuEMCAJkNqH7ZLWHboNPWzAumHdbj7UkWnHqSwZ+kgzGP7vpSXbcYt+wBeKfO/5kaJa9qVpooNDds4Sw3XVWDBoXQMik+VlyqxJ2edUAlR1o7SF1hm8tUpnJXZQaFVDyq6IT+mYK40p68FcSWPhkAlHYF3JEi7hRFwussUaFjsUQi1WF/CMcePqLeqnhC0RNpuNB/cfQOEkt5WS4Jo8s8Nvlito+yLM/x35mBzc6Uzm5NgESx/an5ndRSG5XHV3wUn3on4w9Uw/JCf9J3IXg1YSh7HSEOlgsW4EyfmRJnl1AC4yY2jQhcAjVFQ3ZxylRQ17Z2xV/B+PD2ckhChhNwTDxZBOMwQwtHYObTsbQEc2QjmJe+h0OvEApO9lYobWXmWS8xk32TpraVRXXFT8npqZ3wnZ/OePg7kkDuj3+cHDu/wkHt2MURLP5szWtMS0XkVVRnujJG26v8OUcVU3lUD9q+kvmhadug+iKctoNx9++JzVDtdjnu+Q37+Q35tjn0vZb40G9YEewlSzmS7RhvL17Q0eKZ6KtcqdIPQbxT9olHC9xwD76mROtmc47/a7f6E0ob/m+mhRmrGp3qjfRo9PGT3Xb2+0frL7Mfo0bHHHukf3ZGH4

### Workaround

Select 13.9.0 from the dropdown. 

### System Info

```Shell
Browser
```

### Used Package Manager

npm

### Validations

- [x] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [x] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [x] Read the [docs](https://vueuse.org/guide).
- [x] Check that there isn't [already an issue](https://github.com/vueuse/vueuse/issues) that reports the same bug to avoid creating a duplicate.
- [x] Make sure this is a VueUse issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to https://github.com/vuejs/core instead.
- [x] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vueuse/vueuse/discussions).
- [x] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

### LINKED ISSUE #21: BUG | Playground does not work for 14.0.0 vue use.
Eg. This is the link from the Vue Use docs: 

https://playground.vueuse.org/?vueuse=14.0.0

(Note the URL specifies 14.0.0 as the vue use version). 

We see nothing in the preview section, and we can see an error in the console

Image

The error is: 

```
cdn.jsdelivr.net/npm/@vueuse/core@14.0.0/index.mjs:1  
Failed to load resource: the server responded with a status of 404 ()
```

This is likely the same issue as #18  - but this is a bit more serious at it's an official release. 

(This issue made it harder for me to create a reproduction for this issue: https://github.com/vueuse/vueuse/issues/5148 because I couldn't just create a sandbox link).

### PR DESCRIPTION
**Pull request by cosine7**
fixes #21 fixes #18

by fetching VueUse package.json module field on version changes.
There might be a better solution, but this makes it work for now.

### CODE REVIEW

File: app/pages/index.vue [hunk 1]
```diff
@@ -40,8 +40,9 @@ const vueUsePackages = [
 ]
 
 function generateVueUseImportCDNs() {
+  const file = Number.parseInt(vueuseVersion.value) >= 13 ? '+esm' : 'index.mjs'
```
Comment (OrbisK) [inline app/pages/index.vue]: I think we cant use `parseInt` here: `latest`, `13.0.0`, `14.0.0-alpha.1`

**Review by OrbisK — APPROVED** [review]
